import { showTime } from "../common";
import { defineApp } from "../types";

export default defineApp({
  id: "life",
  title: "Game of Life",
  description: "Conway's Game of Life, growing round the cube.",
  icon: "bacterium",
  category: "worlds",
  script: "life/showLife.ts",
  params: [
    {
      id: "pattern",
      label: "Start with",
      type: "select",
      flag: "--pattern",
      default: "",
      choices: [
        { value: "", label: "a random grid" },
        { value: "glider" },
        { value: "lwss", label: "lightweight spaceship" },
        { value: "block" },
        { value: "blinker" },
        { value: "toad" },
        { value: "beacon" },
      ],
    },
    {
      id: "restartOnStable",
      label: "Start anew when it comes to rest",
      type: "boolean",
      flag: "--restartOnStable",
      default: true,
    },
    {
      id: "density",
      label: "Filled at the start",
      type: "number",
      flag: "--density",
      min: 0,
      max: 1,
      step: 0.05,
      placeholder: "0.25",
      help: "The share of cells alive in a random grid, 0 to 1.",
      showIf: { pattern: "" },
      advanced: true,
    },
    {
      id: "msPerFrame",
      label: "Time per generation",
      type: "number",
      flag: "--msPerFrame",
      min: 1,
      unit: "ms",
      placeholder: "150",
      advanced: true,
    },
    {
      id: "rule",
      label: "Rule",
      type: "text",
      flag: "--rule",
      placeholder: "B3/S23",
      help: "Born with / survives with this many neighbours.",
      advanced: true,
    },
    showTime,
  ],
});
