import { showTime, zenith } from "../common";
import { defineApp } from "../types";

export default defineApp({
  id: "weather",
  title: "Weather",
  description: "The weather now and to come, a page on every face.",
  icon: "cloud-sun",
  category: "info",
  script: "weather/showWeather.ts",
  startLabel: "Show weather",
  params: [
    {
      id: "location",
      label: "Place",
      type: "text",
      flag: "--location",
      default: "Almere-Buiten",
      placeholder: "Almere-Buiten",
      help: "A name to look up on the web.",
    },
    {
      id: "temperatureUnit",
      label: "Temperature in",
      type: "select",
      flag: "--temperatureUnit",
      default: "c",
      choices: [
        { value: "c", label: "°C" },
        { value: "f", label: "°F" },
      ],
    },
    {
      id: "windUnit",
      label: "Wind in",
      type: "select",
      flag: "--windUnit",
      default: "kmh",
      choices: [
        { value: "kmh", label: "km/h" },
        { value: "ms", label: "m/s" },
        { value: "mph", label: "mph" },
        { value: "kn", label: "kn" },
      ],
    },
    {
      id: "pages",
      label: "Pages",
      type: "multiselect",
      flag: "--pages",
      join: ",",
      default: ["now", "hours", "days", "wind", "rain", "sun"],
      choices: [
        { value: "now" },
        { value: "hours" },
        { value: "days" },
        { value: "wind" },
        { value: "rain" },
        { value: "sun" },
      ],
      advanced: true,
    },
    {
      id: "pageTime",
      label: "Turn the pages every",
      type: "number",
      flag: "--pageTime",
      min: 1,
      unit: "s",
      placeholder: "30",
      advanced: true,
    },
    {
      id: "refresh",
      label: "Fetch the weather every",
      type: "number",
      flag: "--refresh",
      min: 1,
      unit: "min",
      placeholder: "10",
      advanced: true,
    },
    zenith("Which way is up, for the pages to be the right way up."),
    showTime,
  ],
});
